apiVersion: v1
kind: Service
metadata:
  name: app2-dev-service
  namespace: dev
  labels:
    app: app2-dev-service
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: NodePort
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 5001
  selector:
    app: app2-dev
